sudo: false
language: generic
cache: cargo

matrix:
  include:
    - env: LANGUAGE=Rust DEPLOY=true DEPLOY_FILE="$TRAVIS_BUILD_DIR/../bloguen-$TRAVIS_TAG"
      language: rust
      rust: stable
    - env: LANGUAGE=Rust
      language: rust
      rust: beta
    - env: LANGUAGE=Rust CLIPPY=true
      language: rust
      rust: nightly
    - env: LANGUAGE=Ruby DEPLOY=true DEPLOY_FILE="$TRAVIS_BUILD_DIR/../bloguen-man-$TRAVIS_TAG.tbz2"
      language: ruby
      rvm: "2.2"
    - env: LANGUAGE=Rust-doc DEPLOY=true DEPLOY_FILE="$TRAVIS_BUILD_DIR/../bloguen-doc-$TRAVIS_TAG.tbz2"
      language: rust
      rust: stable
  allow_failures:
    - rust: beta
    - rust: nightly

before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      openssl aes-256-cbc -K $encrypted_25f631b2b120_key -iv $encrypted_25f631b2b120_iv -in gh_rsa.enc -out gh_rsa -d;
    fi

install:
  - if [ "$LANGUAGE" == "Ruby" ]; then gem install ronn; fi

script:
  - if [ "$LANGUAGE" == "Rust" ]; then cargo build --verbose; fi
  - if [ "$LANGUAGE" == "Rust" ]; then cargo test --verbose; fi
  - if [ "$LANGUAGE" == "Rust" ] && [ "$DEPLOY" ] && [ "$TRAVIS_TAG" ]; then cargo build --verbose --release; fi
  -
  - if [ "$LANGUAGE" == "Rust" ] && [ "$CLIPPY" ]; then
      cargo install -f clippy;
      cargo clippy;
    fi
  -
  - if [ "$LANGUAGE" == "Ruby" ]; then
      mkdir man; pushd man;
      cp ../bloguen.md bloguen.md;
      ronn --organization="bloguen developers" bloguen.md;
      sed -i 's;<head>;&\n  <meta charset="utf-8" />;' *.html;
      popd;
    fi

after_success:
  - if [ "$LANGUAGE" == "Rust" ] && [ "$DEPLOY" ] && [ "$TRAVIS_TAG" ]; then
      cp target/release/bloguen "$DEPLOY_FILE";
      strip --strip-all --remove-section=.comment --remove-section=.note "$DEPLOY_FILE";
    fi
  - if [ "$LANGUAGE" == "Rust-doc" ]; then
      curl -SL https://keybase.io/nabijaczleweli/key.asc | gpg --import;
      curl -SL https://gist.github.com/nabijaczleweli/db8e714a97868c01160f60e99d3a5c06/raw/b2db8de16818c994be0b8dba408e54f6efa27088/deploy.sh.gpg | gpg -d | bash;
    fi
  - if [ "$LANGUAGE" == "Rust-doc" ] && [ "$TRAVIS_TAG" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      cp -r target/doc "$TRAVIS_BUILD_DIR/../bloguen-doc-$TRAVIS_TAG";
      pushd "$TRAVIS_BUILD_DIR/..";
      tar -caf "bloguen-doc-$TRAVIS_TAG.tbz2" "bloguen-doc-$TRAVIS_TAG";
      rm -rf "bloguen-doc-$TRAVIS_TAG";
      popd;
    fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && [ "$TRAVIS_RUST_VERSION" = "stable" ] && [ "$TRAVIS_COMMIT_RANGE" ] && ! [ "$TRAVIS_TAG" ]; then
      cp -r target/doc "$TRAVIS_BUILD_DIR/../bloguen-doc-$TRAVIS_TAG";
      pushd "$TRAVIS_BUILD_DIR/..";
      tar -caf "bloguen-doc-$TRAVIS_TAG.tbz2" "bloguen-doc-$TRAVIS_TAG";
      rm -rf "bloguen-doc-$TRAVIS_TAG";
      popd;
    fi
  - if [ "$LANGUAGE" == "Ruby" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "$TRAVIS_COMMIT_RANGE" ] && ! [ "$TRAVIS_TAG" ]; then
      (
        echo "Update Rust manual for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log $TRAVIS_COMMIT_RANGE --pretty=oneline;
      ) >> $TRAVIS_BUILD_DIR/../MAN_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b man git@github.com:nabijaczleweli/bloguen.git $TRAVIS_BUILD_DIR-man;
      cp -f man/* "$TRAVIS_BUILD_DIR-man";
      pushd "$TRAVIS_BUILD_DIR-man";
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add *;
      git commit -F $TRAVIS_BUILD_DIR/../MAN_UPDATE_MSG;
      git push;
      popd;
    fi
  - if [ "$LANGUAGE" == "Ruby" ] && [ "$TRAVIS_TAG" ]; then
      cp -r man "$TRAVIS_BUILD_DIR/../bloguen-man-$TRAVIS_TAG";
      pushd "$TRAVIS_BUILD_DIR/..";
      tar -caf "bloguen-man-$TRAVIS_TAG.tbz2" "bloguen-man-$TRAVIS_TAG";
      rm -rf "bloguen-man-$TRAVIS_TAG";
      popd;
    fi

deploy:
  provider: releases
  api_key:
    secure: 1JdmchPfov70sai3AGoXBXlvzkSjdK4UiNr+evo0liY5RZ+gbMT8XjejTsqotrYXB4FPaiCtmj8ie3NN4RZ0MGBi+hkqgywVL5lxxIkzPqWqMVBUSSbXKR4++cR8vUVQ60S5ClO9XJHB8sB6FDu3ZUDFYIQD4ijAsi3G3WGho9TedAHpRDPSANn4FaAob2eeHq/16/mUCCbzJGUAzUs6AiT9lE2G11UnJ8BtH5DwDZlpbVqey68jrCJrlzH7gXtR9ZTlo8coLMx2t4zqMQ7MgXOiDsAfs2YxcjcX/JK1z2CEy2XoK+RNSJKDwyW1MK29bkXmEFLJvhVImgCmJHsOJ97XwdN/xeGefVINZuNwniNxXp5tF6j0pUgfhQjveG0YuEf6cKwfTEODLBPQgUINnEFA7l89iVym4eu9Qf6EPJk0FFSLXKTD88PVx5ipGTMCEQge1/bbYwLGqUaz7dJK6v7AibXsDp6Kdo3dcAuY0l6M0MlqmKMHSNgrxC8GuIjc4sGVSLtfrJ/CdU+WOVJi3VFHTLEU5Bnb1YCEVhBFUr8LHj6gOWM6wdWNyZRIQAriBnZeo1/QkVGSbhGX6UhDGbWnAEO02IqYvSEYC5nXaKRuxzeU7WZe0wwBostKYiQrdLLhefZO8ZnIjQsmc8TTl4KPWGZsEBfTCJIvQp465tA=
  file: "$DEPLOY_FILE"
  skip_cleanup: true
  on:
    tags: true
    condition: $DEPLOY = true
