.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BLOGUEN" "1" "October 2018" "bloguen developers" ""
.
.SH "NAME"
\fBbloguen\fR \- Generate a blogue from Markdown (again)
.
.SH "SYNOPSIS"
\fBbloguen\fR IN_DIR OUT_DIR \fIOPTIONS\fR
.
.SH "DESCRIPTION"
Generate a blogue from Markdown (again)\.
.
.SH "OPTIONS"
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/bloguen/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/bloguen\fR>
